const cthulhuSkillsList = [
	"Accounting",
	"Anthropology",
	"Appraise",
	"Archaeology",
	"Art/Craft",
	"Charm",
	"Climb",
	"Credit Rating",
	"Cthulhu Mythos",
	"Disguise",
	"Dodge",
	"Drive Auto",
	"Electrical Repair",
	"Fast Talk",
	"Fighting (Brawl)",
	"Firearms (Handgun)",
	"Firearms (Rifle/Shotgun)",
	"First Aid",
	"Heavy Weapons",
	"History",
	"Intimidate",
	"Jump",
	"Language (Own)",
	"Law",
	"Library Use",
	"Listen",
	"Locksmith",
	"Mechanical Repair",
	"Medicine",
	"Natural World",
	"Navigate",
	"Occult",
	"Operate Heavy Machinery",
	"Persuade",
	"Pilot",
	"Psychology",
	"Psychoanalysis",
	"Ride",
	"Safe Cracking",
	"Science",
	"Sleight of Hand",
	"Spot Hidden",
	"Stealth",
	"Swim",
	"Throw",
	"Track",
];

export default cthulhuSkillsList;
